name: CI/CD Pipeline (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-main:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ai_agent/requirements.txt
        python -m spacy download en_core_web_sm
        
    - name: Run continuous operation
      run: |
        python ai_agent/continuous_operation.py
