name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ai_agent/requirements.txt
        python -m spacy download en_core_web_sm
        
    - name: Run continuous operation
      run: |
        python ai_agent/continuous_operation.py

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Lint with flake8
      run: |
        flake8 ai_agent/ --count --max-line-length=120 --statistics
#       run: |
#         flake8 . --count --max-line-length=120 --statistics
