name: 24/7 Continuous Operation (Windows)

on:
  schedule:
    - cron: '0 */6 * * *'   # every 6 hours, at minute 0 (UTC)
  workflow_dispatch:       # allow manual runs too
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-continuous-windows:
    runs-on: windows-latest
    timeout-minutes: 360    # 6-hour max per run
    concurrency:
      group: continuous-windows
      cancel-in-progress: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ai_agent/requirements.txt
          python -m spacy download en_core_web_sm

      - name: Run continuous operation
        run: python ai_agent/continuous_operation.py
